### PR TITLE
GODRIVER-2839 Document 1.13 non-support for go mod tidy

### PR DESCRIPTION
**Pull request by prestonvasquez**
GODRIVER-2839

## Summary

The Go Driver will not support using "go mod tidy" for Go v1.13. The driver depends on github.com/klauspost/compress v1.13.6 which uses io/fs. Using "go mod tidy" under these conditions is a known issue in the go/golang community, see issues [#44557](https://github.com/golang/go/issues/44557) for more information.

This ticket also updates the compile-check target to provide more thorough build coverage.

## Background & Motivation

Adding "go mod tidy" to the build-check-compile target revealed a build error introduced by klauspost/compress v1.13.6. This dependency was originally bumped to v1.13.6 in PR #759 to resolve the dynamic linking issues [here](https://github.com/klauspost/compress/issues/428).

### CODE REVIEW

File: etc/compile_check.sh [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+
+	# Check build with various architectures.
+	GOOS=linux GOARCH=386 ${GC} build $(BUILD_TAGS) ./...
+	GOOS=linux GOARCH=arm ${GC} build $(BUILD_TAGS) ./...
+	GOOS=linux GOARCH=arm64 ${GC} build $(BUILD_TAGS) ./...
+	GOOS=linux GOARCH=ppc64le ${GC} build $(BUILD_TAGS) ./...
+	GOOS=linux GOARCH=s390x ${GC} build $(BUILD_TAGS) ./...
+
+	# Reset any changes to the "go.mod" and "go.sum" files.
+	git checkout HEAD -- go.mod
```
Comment (matthewdale) [inline etc/compile_check.sh:67]: We should be able to run these scripts locally to debug issues. This could lead to unintentionally deleting changes in `go.mod` that someone had made.

What scenario are we testing by running `go mod tidy` with different `-go` modes?

File: etc/compile_check.sh [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+
+	# Remove the binaries.
+	rm compilecheck
+	rm compilecheck.so
+
+	# Change the directory back to the working directory.
+	cd ${WD}
```
Comment (matthewdale) [inline etc/compile_check.sh:74]: Optional: This can probably be replaced with `cd -`.

File: etc/compile_check.sh [hunk 3]
```diff
@@ -0,0 +1,79 @@
+#!/usr/bin/env bash
+set -e # exit when any command fails
```
Comment (matthewdale) [inline etc/compile_check.sh:2]: Optional: Consider also using `set -x` to show all the commands being run.

File: etc/compile_check.sh [hunk 4]
```diff
@@ -0,0 +1,79 @@
...
+
+# dev_compile_check will attempt to build in the development environment. This
+# check will only run on environments where the Go version is greater than or
+# equal to the DEV_MIN_VERSION.
+function dev_compile_check {
+	MACHINE_VERSION=`${GC} version | { read _ _ v _; echo ${v#go}; }`
+
+	if [ $(version $MACHINE_VERSION) -lt $(version $DEV_MIN_VERSION) ]; then
+		return
+	fi
```
Comment (matthewdale) [inline etc/compile_check.sh:23]: I'm concerned this logic could lead to builds that pass without actually running anything. For example, if a dev is using Go 1.18, they may run this compile check script and assume that everything worked fine because it didn't return any errors. Instead, they should see any relevant compilation errors.

File: etc/compile_check.sh [hunk 5]
```diff
@@ -0,0 +1,79 @@
...
+# check will only run on environments where the Go version is greater than or
+# equal to the given version.
+function compile_check {
+	GO111MODULE=$1
+	VERSION=$2
+	MACHINE_VERSION=`${GC} version | { read _ _ v _; echo ${v#go}; }`
+
+	if [ $(version $MACHINE_VERSION) -lt $(version $VERSION) ]; then
+		return
+	fi
```
Comment (matthewdale) [inline etc/compile_check.sh:40]: I'm concerned this logic could lead to builds that pass without actually running anything. For example, when we update the Evergreen CI Go version from 1.19 to 1.20, if we forget to also update this script, `compile_check` will return without actually building anything because the Go version doesn't match any of the expected versions. Additionally, we want to be able to run these scripts locally with any supported version of Go to debug issues.

Is there a way to just skip running `go mod tidy` on Go 1.13 without tying the script to specific Go versions?

Ideas:
Remove the `$VERSION` argument and update the `go mod tidy` block to:
```
if [ "$MACHINE_VERSION" != 1.13 ]; then
	go mod tidy
fi
```

File: etc/compile_check.sh [hunk 6]
```diff
@@ -0,0 +1,79 @@
...
+
+	# Check build with tags.
+	go build $(BUILD_TAGS) ./...
+
+	# Check build with various architectures.
+	GOOS=linux GOARCH=386 ${GC} build $(BUILD_TAGS) ./...
+	GOOS=linux GOARCH=arm ${GC} build $(BUILD_TAGS) ./...
+	GOOS=linux GOARCH=arm64 ${GC} build $(BUILD_TAGS) ./...
+	GOOS=linux GOARCH=ppc64le ${GC} build $(BUILD_TAGS) ./...
+	GOOS=linux GOARCH=s390x ${GC} build $(BUILD_TAGS) ./...
```
Comment (matthewdale) [inline etc/compile_check.sh:64]: Add `amd64` to this list so it does the same cross-compile checks on `arm64` and `amd64` hosts (i.e. don't assume it's running on `amd64`).

File: internal/test/compilecheck/main.go
Comment (matthewdale) [inline internal/test/compilecheck/main.go:1]: Optional: Consider importing more Go driver packages to make `compilecheck` more realistic.

E.g.
```go
package main

import (
	"context"
	"fmt"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/mongo"
	"go.mongodb.org/mongo-driver/mongo/options"
)

func main() {
	_, _ = mongo.Connect(context.Background(), options.Client())
	fmt.Println(bson.D{{Key: "key", Value: "value"}})
}
```

File: etc/compile_check.sh [hunk 7]
```diff
@@ -0,0 +1,79 @@
...
+	GO111MODULE=on ${GC} build ./...
+	GO111MODULE=on ${GC} build ${BUILD_TAGS} ./...
+}
+
+# compile_check will attemps to build the the internal/test/compilecheck project
+# using the provided go version. This is to simulate a end-to-end use case. This
+# check will only run on environments where the Go version is greater than or
+# equal to the given version.
+function compile_check {
+	GO111MODULE=$1
```
Comment (matthewdale) [inline etc/compile_check.sh:34]: This argument appears unused.

File: etc/compile_check.sh [hunk 8]
```diff
@@ -0,0 +1,79 @@
...
+# equal to the DEV_MIN_VERSION.
+function dev_compile_check {
+	MACHINE_VERSION=`${GC} version | { read _ _ v _; echo ${v#go}; }`
+
+	if [ $(version $MACHINE_VERSION) -lt $(version $DEV_MIN_VERSION) ]; then
+		return
+	fi
+
+	GO111MODULE=on ${GC} build ./...
+	GO111MODULE=on ${GC} build ${BUILD_TAGS} ./...
```
Comment (matthewdale) [inline etc/compile_check.sh:26]: The `GO111MODULE` behavior is enabled by default on Go 1.13+ if there is a `go.mod` file (see [details](https://go.dev/doc/go1.13#modules)). Is there a reason we need to explicitly enable it?

File: etc/compile_check.sh (hunk 6 above)
Comment (matthewdale) [inline etc/compile_check.sh:64]: The `$(BUILD_TAGS)` in bash attempts to run the command `BUILD_TAGS` instead of doing a replacement like in Makefiles, leading to errors like:
> etc/compile_check.sh: line 57: BUILD_TAGS: command not found

Cross-compiling with build tags that enable C builds won't work on Evergreen CI hosts (or on local workstations usually), so it's best to just remove those.
```suggestion
	GOOS=linux GOARCH=386 ${GC} build ./...
	GOOS=linux GOARCH=arm ${GC} build ./...
	GOOS=linux GOARCH=arm64 ${GC} build ./...
	GOOS=linux GOARCH=ppc64le ${GC} build ./...
	GOOS=linux GOARCH=s390x ${GC} build ./...
```

File: etc/compile_check.sh [hunk 9]
```diff
@@ -0,0 +1,70 @@
...
+# version will flatten a version string of upto 4 components for inequality
+# comparison.
+function version {
+	echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }';
+}
+
+# dev_compile_check will attempt to build in the development environment. This
+# check will only run on environments where the Go version is greater than or
+# equal to the DEV_MIN_VERSION.
+function dev_compile_check {
```
Comment (matthewdale) [inline etc/compile_check.sh:18]: Optional: The `dev_compile_check` now seems redundant with the `build` Makefile target. Consider removing it.

File: etc/compile_check.sh (hunk 4 above)
Comment (matthewdale) [reply etc/compile_check.sh:23]: Now that `compile_check` runs most commands with any version of Go, I think this is safer to keep. However, as noted in my other comment, `dev_compile_check` seems redundant with other Makefile targets now and could probably be removed. Consider this comment thread resolved, tho.

**Review by matthewdale — APPROVED** [review]
Looks good 👍

File: etc/compile_check.sh [hunk 10]
```diff
@@ -0,0 +1,55 @@
...
+# This check will only run on environments where the Go version is greater than
+# or equal to the given version.
+function compile_check {
+	# Change the directory to the compilecheck test directory.
+	cd ${COMPILE_CHECK_DIR}
+
+	MACHINE_VERSION=`${GC} version | { read _ _ v _; echo ${v#go}; }`
+
+	# If the version is not 1.13, then run "go mod tidy"
+	if [ $(version $MACHINE_VERSION) -gt $(version 1.13) ]; then
```
Comment (matthewdale) [inline etc/compile_check.sh:26]: This check appears to not work as expected in the Go 1.13 build because the current logic considers 1.13.15 > 1.13. The more correct check is that the Go version is >= 1.15 because that's the oldest minor version with the backported fix.
```suggestion
	if [ $(version $MACHINE_VERSION) -ge $(version 1.15) ]; then
```
P.S. The actual backport versions are [Go 1.15.10](https://github.com/golang/go/issues/44792) and [Go 1.16.2](https://github.com/golang/go/issues/44793), but I don't think we need to be that specific.
